--- #YAML:1.0
name:                Config-Merge
version:             1.00
abstract:            load a configuration directory tree containing
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Config::Any:                   0.07
    Data::Alias:                   1.01
    File::Spec:                    0
    Storable:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    -  Clinton Gormley <clint@traveljury.com>
