---
abstract: 'load a configuration directory tree containing YAML, JSON, XML, Perl, INI or Config::General files'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Merge
recommends:
  Config::General: '0'
  Config::Tiny: '0'
  JSON: '0'
  JSON::XS: '0'
  XML::Simple: '0'
  YAML: '0'
  YAML::Syck: '0'
requires:
  Config::Any: '0.07'
  File::Glob: '0'
  File::Spec: '0'
  Storable: '0'
  overload: '0'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/clintongormley/ConfigMerge/issues
  repository: git://github.com/clintongormley/ConfigMerge.git
version: '1.03'
